server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database_test
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update